- .gitignore
- .travis.yml
- Makefile
- cmd/dcrlncli/commands.go
- cmd/dcrlncli/password.go
- cmd/dcrlncli/password_windows.go
- lntest/node.go
- release.sh
> Fix release script

- chainregistry.go
- config.go
- docs/INSTALL.md
- lntest/node.go
- sample-lnd.conf
decred.active was a mandatory config item, which must always
be set to true. Added no functionality.
(**edit:** pushed one more commit so this Closes #13)
> remove decred.active config.

- chainregistry.go
- fundingmanager.go
- htlcswitch/link.go
- lnrpc/walletrpc/walletkit.pb.go
- lnrpc/walletrpc/walletkit.proto
- lnrpc/walletrpc/walletkit_server.go
- lnwallet/channel.go
- lnwallet/channel_test.go
- lnwallet/fee_estimator.go
- lnwallet/interface.go
- lnwallet/interface_test.go
- lnwallet/parameters.go
- lnwallet/reservation.go
- lnwallet/test_utils.go
- lnwallet/wallet.go
- lnwire/update_fee.go
- rpcserver.go
- sweep/sweeper_test.go
- sweep/txgenerator.go
only affects comments and log lines.
walletkit.pb.go regenerated with updated comment.
Closes #10
> change units from kw to KB.

- lnd_test.go
This improves the reliability of the switch to offline delivery test by
ensuring only Carol can connect to Dave (and not vice-versa) and that
their connection is up before attempting to complete the final payment.
This is necessary before upstream changes to dcrd's connmgr package
to correctly cancel outstanding connection attempts are merged.
Currently this test fails depending on the exact timings of the code
execution, which might cause the nodes to be disconnected at the exact
time the last payment is attempted. By only allowing connections on the
Carol -> Dave direction, we prevent this situation from arising.
The relevant upstream commits alluded to in the original message are here: https://github.com/decred/dcrd/pull/1724
> itest: Fix switch to offline delivery test

- lnd_test.go
This splits the testRevokedCloseRetributionRemoteHodl into two tests and
fixes them accordingly.
The first test ensures that Carol (the party relaying an old, invalid
and revoked commitment state) does _not_ have a chance to broadcast
second-level HTLC-redeeming transactions. This ensures Dave's (the
breached counterparty) justice transaction redeems entirely from the
commitment transaction and is the only transaction in the mempool.
The second test ensures that Carol has enough time to broadcast
second-level HTLC-redeeming transactions before Dave detects the
breached state and sends a sweeping justice transaction that also
redeems from them (along with the funds still time-locked in the
commitment).
Previously these two situations were tested in a single test but
unreliably. It was a …
> itest: Split revoked uncooperative close retrib

- .github/workflows/go.yml
- .gitignore
- Makefile
- chainregistry.go
- fundingmanager.go
- lntest/harness.go
- lntest/itest/lnd_test.go
- lntest/node.go
- lntest/timeouts.go
- lnwallet/dcrwallet/config.go
- lnwallet/dcrwallet/wallet.go
- lnwallet/interface.go
- lnwallet/interface_test.go
- lnwallet/remotedcrwallet/config.go
- lnwallet/remotedcrwallet/wallet.go
- lnwallet/remotedcrwallet_test.go
- lnwallet/wallet.go
- mock.go
- watchtower/wtclient/client_test.go
This includes the commit from #48
Hopefully these improve flakiness on Github Actions CI.
> Fix GitHub actions

- build/version.go
This updates the built-in build version to v0.2.0 which will be the next
released version.
> build: Update to 0.2.0

- README.md
update/change
to it
and Commenting](../blob/master/docs/code_contribution_guidelines.md#CodeDocumentation)
section of the Code Contribution Guidelines
(error paths) conditions (if applicable)
prevent regressions
provided
changes (if applicable)
> Fixed broken link to docker docs

- lnrpc/walletrpc/walletkit_server.go
- lntest/itest/lnd_test.go
- lntest/timeouts.go
- lnwallet/dcrwallet/config.go
- lnwallet/dcrwallet/rpcsync.go
- lnwallet/dcrwallet/wallet.go
- lnwallet/interface_test.go
- server.go
This fixes further test flakiness brough up by running on github actions.
> More improvement to tests after github actions failures

- Dockerfile
Updates Dockerfile to use dcrlnd rather then lnd.
> dcrlnd: Update Dockerfile 

- chainparams.go
- config.go
- sample-dcrlnd.conf
> config: dcrwallet updated with activenetparam

- chainregistry.go
- config.go
- docs/INSTALL.md
- docs/QUICKSTART.md
- lnd.go
- lntest/itest/lnd_test.go
- lntest/node.go
- rpcserver.go
- sample-dcrlnd.conf
- server.go
- subrpcserver_config.go
@matheusd can you test this commit more, I don't know all possible cases that this commit can crash other things.
resolve #14
> multi: remove chain namespacing

- cmd/dcrlncli/main.go
- config.go
- docker/README.md
- docs/recovery.md
- lnd.go
- sample-dcrlnd.conf
This is pull request for #70 and #71 as they were somewhat connected.
> Network command line switches for `dcrlnd` and `dcrlncli` which closes #70 #71

- build/version.go
> build: Bump to minor version 3

- build/version.go
- lnwallet/dcrwallet/rpcsync.go
- lnwallet/dcrwallet/wallet.go
This updates the version of the release-v0.2 branch to v0.2.1 and brings in the fix done over in PR #75
> Bring bugfix to v0.2.1

- docker/dcrd/start-dcrd.sh
- docker/dcrlnd/start-dcrlnd.sh
- docker/dcrwallet/start-dcrwallet.sh
With this you can expose the services outside the containers,
to use in docker host with localhost sintaxe.
> docker: use 0.0.0.0 to all rpclisten conf

- lntest/itest/lnd_test.go
This ensures the Carol and Dave nodes created in the single_hop series
of tests are synced to the latest chain tip generated by the miner
before creating the route that will eventually be used for payments.
This prevents a flake during SPV tests where slow processing of blocks
by Carol could cause the generated route to have a final CLTV delta too
short for Dave to accept.
While at it, we switch the test to use the default CLTV delta provided
by QueryRoutes which is now the global default CLTV.
> itest: Sync nodes to chain during singleHop tests

- Makefile
- go.mod
- go.sum
- internal/testutils/remotewallet.go
- lntest/node.go
This updates the packages and test binaries to use the versions included
in the v1.6.0-rc2 release.
> multi: Update to v1.6.0-rc2 packages

- watchtower/wtclient/client.go
- watchtower/wtclient/client_test.go
- watchtower/wtclient/session_negotiator.go
Port of upstream commit https://github.com/lightningnetwork/lnd/pull/4789
> wtclient: schedule ForceQuit during Stop

- README.md
- docs/INSTALL.md
> docs: Add missing protocol and BOLT compliance

- build/version.go
This is done in preparation for an upcoming release.
> build: Bump to v0.3.3

- chainntnfs/chainscannotify/csnotify.go
This adds a mutex to protect against concurrent access to the tipTxs
map.
This solves the issue triggered in the CI run for #141
> chainscannotify: Add mutex to tip txs map

- .gitignore
- config.go
- lnd.go
This allows generating a heap pprof dump at the end of execution.
> main: Add --memprofile option

- Makefile
- internal/testutils/simnet_miner.go
This required fixing the simnet miner to account for the ticket exhaustion error that could happen during mining.
> make: Update dcrd and dcrwallet test versions to latest

- .github/workflows/docker.yml
- Makefile
- build/version.go
- go.mod
- go.sum
Additionally, dcrlnd is bumped to v0.3.8
> build: Update deps for v1.7.7 release

- cmd/dcrlncli/main.go
> dcrlncli: Remove additional newline

- Makefile
- build/version.go
- go.mod
- go.sum
> Update to version v0.7.2

- lnwallet/dcrwallet/spvsync.go
The SPVSyncer.Run() method would not previously error out when running out of peers. Now it does, leading to an error when re-running it.
This was [fixed in dcrwallet](https://github.com/decred/dcrwallet/commit/2198be020f41997529fac234224d903948eff99d), but dcrlnd needs a copy of that code (because spvLoop lives in the main package).
> dcrwallet: Fix spv syncer loop panic
