- brontide/noise.go
- chainntnfs/dcrdnotify/dcrd_dev.go
- chainntnfs/interface_test.go
- chainparams.go
- chainregistry.go
- channeldb/graph.go
- channeldb/graph_test.go
- channeldb/nodes.go
- cmd/dcrlncli/commands.go
- contractcourt/contract_resolvers.go
- discovery/gossiper.go
- discovery/gossiper_test.go
- fundingmanager.go
- fundingmanager_test.go
- lnwallet/dcrwallet/wallet.go
- lnwallet/interface.go
- lnwallet/test_utils.go
- mock.go
- routing/ann_validation.go
- sample-lnd.conf
- server.go
- utxonursery.go
- zpay32/amountunits.go
- Update "btc" => "dcr" and "bitcoin" => "decred" in many places. Mostly in comments but also some variable names.
- Remove type `channelProof` from `fundingmanager.go`. It isn't used.
- Remove some references to litecoin
> removing btc/ltc references

- chainregistry.go
- discovery/bootstrapper.go
- server.go
This disables the dns bootstrapper on current dcrlnd networks since
the corresponding seeders aren't up yet.
It does so by clearing the hard coded DNS seeder addresses and adding a
special case that exits early if no addresses are returned by the
bootstrapping process.
It also fixes a logic error condition where bootstrapping wasn't
re-enabled after the backoff period after the initial bootstrapping
phase.
> discovery: Disable DNS boostrapper

- lnd_test.go
This fixes a possible panic when a timeout occurs in
testInvoiceRoutingHints.
> itest: Fix possible panic

- config.go
Fix types of flags in ConfigFile, we need one type of each, short and long.
With this fix we can use:
```
dcrlnd -C
or
dcrlnd --configfile
```
> Fix configfile flags

- Makefile
Makes it so that `make lint` execute the exact same directives as travis will.
> make: Match lint target to travis rules

- lnd.go
- lnwallet/dcrwallet/wallet.go
- lnwallet/interface.go
- lnwallet/interface_test.go
- mock.go
This adds the InitialSyncChannel function to the WalletController
interface, so that wallet drivers can signal that all initial sync
procedures have completed.
This is used as a replacement for the busy wait on IsSynced(), which is
less than ideal from a performance point of view and also allows faster
node startup during integration tests.
> lnwallet: Add InitialSyncChannel to WalletController

- chainregistry.go
- channeldb/keychain.go
- channeldb/keychain_test.go
- keychain/derivation.go
- keychain/hdkeyring.go
- keychain/hdkeyring_test.go
- keychain/interface_test.go
- keychain/test_utils.go
- lnwallet/dcrwallet/config.go
- lnwallet/dcrwallet/keychain.go
- lnwallet/dcrwallet/keychain_test.go
- lnwallet/dcrwallet/signer.go
- lnwallet/dcrwallet/wallet.go
- lnwallet/interface_test.go
The main goal for this changeset is to move the keyring implementation (which requires an active and unlocked backing dcrwallet) from the keychain package to the lnwallet/dcrwallet package.
This makes the keychain package cleaner, more generic and removes its dependency to dcrwallet packages in particular and allows future keyring implementations to _not_ be based on a local backing dcrwallet. 
It also binds the existing keyring implementation (WalletKeyRing) to the existing wallet driver, which makes sense since it entirely relies on the internal backing wallet.
Another change introduced is that the public keys generated for use within the LN processes are no longer generated inside the backing dcrwallet (via `NextAddress()` calls), but rather on the keyring itself, based on the root …
> Move keyring implementation from keychain to dcrwallet package

- lntest/node.go
- server.go
This makes it so the server.Started() function correctly reports the the server's sub-services have started and removes a now unnecessary wait in harness nodes.
> Use server.Started() to signal server subservices started

- lnwallet/remotedcrwallet/keychain.go
- lnwallet/remotedcrwallet/keychain_test.go
- lnwallet/remotedcrwallet/wallet.go
- sweep/sweeper.go
This switches the remote dcrwallet driver to use the internal branch of
the ln account to derive keys for the payment base key family.
This, coupled with the tweakless mode for remote payment addresses 
recently introduced means the wallet is able to redeem funds after execution of 
the DLP protocol without requiring extra data.
This also changes the key derivation to call the wallet's own
NextAddress function, such that multisig and payment base keys are
derived directly on it and respect the standard gap limit policy so that
onchain fund recovery is more consistent.
> Nodelay keyfam wallet

- lntest/node.go
This changes TCP port selection in integration tests from being
sequential, based on the node ID to being sequential but tested before
assigment.
This should reduce the number of flaky tests that fail due to the port
already being used by another process in the CI server.
> lntest: Use TCP ports not based in nodeID

- lnwallet/dcrwallet/rpcsync.go
- lnwallet/dcrwallet/wallet.go
This fixes an issue where the wallet would lose connection to the
underlying dcrd node and never restart it.
This bug was introduced when upgrading to the wallet v3 package.
The RPCSyncer now correctly attempts to maintain the wallet synchronized
until it is signalled to shutdown.
> dcrwallet: Fix syncer not reconnecting

- docker/README.md
- docs/QUICKSTART.md
Left out this change to the documentation in `QUICKSTART.md` in PR #72
> Fixed documentation to reflect `-n` removed from command line args

- Makefile
- build/version.go
- docs/INSTALL.md
- docs/QUICKSTART.md
Improve some build elements now that build tags have been inverted. This:
- Switches the version metadata to use the new standard for decred software
- Switches the commit data generated by `make` to be less confusing
- Switches the instructions to use `go install` instead of `make` (:tada: :tada:)
> Improve build meta

- .github/workflows/go.yml
- make/testing_flags.mk
This switches the Github Actions CI to perform tests using go versions
1.13 and 1.14 versus the previous 1.12 and 1.13.
> github: Switch to go1.14

- cmd/dcrlncli/commands.go
- cmd/dcrlncli/invoicesrpc_active.go
Fix typos in `dcrlncli` based on #88
> Fix typo in dcrlncli commands

- .gitignore
- chainntnfs/dcrdnotify/dcrd.go
- chainntnfs/dcrdnotify/dcrd_test.go
- chainntnfs/txnotifier.go
- chainscan/csdrivers/dcrwdriver.go
- chainscan/csdrivers/dcrwdriver_test.go
- chainscan/csdrivers/log.go
- chainscan/csdrivers/remotedcrwdriver.go
- chainscan/examples/dcrdhistorical/main.go
- chainscan/examples/dcrwallethistorical/main.go
- chainscan/historical.go
- chainscan/historical_test.go
- chainscan/log.go
- chainscan/multi_test.go
- chainscan/notifier.go
- chainscan/pkscript.go
- chainscan/pkscript_test.go
- chainscan/scanner.go
- chainscan/scanner_test.go
- chainscan/tip.go
- chainscan/tip_test.go
- chainscan/util_test.go
- contractcourt/chain_watcher_test.go
- fundingmanager_test.go
- go.mod
- log.go
Part of #80 
(Still missing some documentation, examples and copyright notice on the package.)
This introduces a new package called `chainscan`. The primary goal for this package is to be able to perform historical and tip-changed-triggered scans of blocks to determine whether they have relevant transactions for the LN node and retrieve the ones that are.
This is an improvement over the existing manual rescan performed by the the dcrd node via LoadTxFilter as done today in dcrlnd in that it checks the cfilters for the wanted targets before attempting to iterate over the block's transactions.
It is also a necessary step towards supporting SPV mode, given that in that mode the LN node does not have access to a full chain.
The package is self-contained and has minimal external dependencies. …
> Add Chainscan package

- .gitignore
- chainntnfs/chainscannotify/csnotify.go
- chainntnfs/chainscannotify/csnotify_dev.go
- chainntnfs/dcrdnotify/dcrd_test.go
- chainntnfs/dcrwnotify/dcrw.go
- chainntnfs/dcrwnotify/driver.go
- chainntnfs/interface_test.go
- chainntnfs/remotedcrwnotify/driver.go
- chainntnfs/remotedcrwnotify/remotedcrw.go
- chainntnfs/test_utils.go
**Rebased on top of #83**
Part of #80 
This adds implementations for the chainntnfs package that use the wallet as source of chain events.
This allows to further decouple dcrlnd from an underlying dcrd, which is a requirement for having a dcrlnd instance running in SPV mode.
> Add wallet-backed chainntnfs implementations

- .gitignore
- routing/chainview/chainscan.go
- routing/chainview/dcrwallet.go
- routing/chainview/interface_test.go
- routing/chainview/log.go
**Rebased on top of #92**
Part of #80 
This introduces a wallet-backed driver for the chainview package so that the wallet can be used as source of data for chain events.
This allows to further decouple dcrlnd from an underlying dcrd, which is a requirement for having a dcrlnd instance running in SPV mode.
> Add wallet-backed chainview drivers

- .github/workflows/go.yml
- chainregistry.go
- config.go
- lntest/embeddedwallet-dcrd.go
- lntest/embeddedwallet-dcrw.go
- lntest/embeddedwallet.go
- lntest/harness.go
- lntest/node.go
- lnwallet/dcrwallet/dcrwchainio.go
- lnwallet/dcrwallet/wallet.go
- lnwallet/remotedcrwallet/remotedcrwchainio.go
- lnwallet/remotedcrwallet/wallet.go
**Rebased on top of #93**
Part of #80 
This switches the main dcrlnd package to use the recently introduced wallet-backed drivers for chain IO operations.
The net result is that chain IO operations are now fully performed by the underlying dcrwallet instance and dcrlnd no longer requires a connection to a running dcrd to perform its job.
For dcrlnd operating in remote wallet mode (such as those running from within Decrediton) the change is automatic.
For dcrlnd operating with an embedded dcrwallet, a new value for the `node` config option (`dcrw`) must be specified to use the new IO mode. Both the old `dcrd` mode and the `dcrw` mode are tested via itests running in the Github Actions CI.
> Switch to wallet-backed chain io in dcrlnd

- .github/workflows/go.yml
- chainregistry.go
- config.go
- lntest/itest/lnd_test.go
- lntest/itest/onchain.go
- lntest/remotewallet-dcrw.go
- lntest/remotewallet-spv.go
- lntest/spv.go
Rebased on top of #94 
Part of #80 
This adds a new `node` config choice that allows running dcrlnd in SPV mode. For the moment, only remote wallets are supported.
> Enable and test SPV mode for remote wallets

- lntest/itest/dcrlnd_maxio_test.go
- rpcserver.go
This switches the checkCanReceiveInvoice/checkCanSendPayment preflight
checks to only verify total bandwidth instead of per-channel bandwidth.
Now that dcrlnd supports both sending and receiving multi-path payments,
it doesn't make sense to look for a specific channel with the required
bandwidth.
> rpcserver: Check in/out total bandwidth instead of per-channel

- docs/release-notes/release-notes-0.3.0.md
This adds a note linking to fixed vulnerabilities disclosed after the
upstream v0.11.0 release.
Close #124
> docs: Note vulnerability disclosures

- ipc.go
I'm pretty sure the idea of ipc.go to allow parent processes like Decrediton to control dcrlnd. Please discard this PR if I got it wrong.
> ipc: Correct comments to talk about dcrlnd

- lnd.go
- lntest/itest/lnd_test.go
- lntest/node.go
This adds a time.Sleep() call before stopping the gRPC server used for
the wallet unlocker service and consequently before closing the
listeners for the given server.
Some gRPC client libraries, such as grpc-js used in nodejs/Electron apps
(i.e. Decrediton) have trouble processing the response to a call if the
socket is closed immediately after the response is returned.
The gRPC library currently used in dcrlnd does not offer any method of
identifying whether there are outstanding calls or clients, therefore we
resort to a simple sleep that, while not fundamentally fixing the
underlying issue, alleviates it for the most common use case.
> lnd: Sleep before stopping wallet unlocker server

- docs/remote_dcrwallet.md
Changes to get the remote dcrwallet instructions working on 1.6.0 RC2. 
- changed cert/key file name references to client-ca throughout.
- dcrwallet.conf: removed authtype option and specified where grpclisten should go.
- added note about having to unlock the wallet through dcrlncli when dcrlnd starts.
> docs: Update remote_dcrwallet.md

- lnd.go
- walletunlocker/service.go
- walletunlocker/service_test.go
> walletunlocker: check account in remote unlock 

- README.md
- contrib/dcrlnd-tmux-3node.sh
This allows quickly building a simulation dcrlnd network, along with
setting up appropriate dcrd and dcrwallet instances to keep the network
going.
> contrib: Add 3-node tmux script

- README.md
- SECURITY.md
Adds a SECURITY.md file which is shown in the [security](../security/policy) tab on github.
> Add SECURITY.md file

- build/log_default.go
- chainregistry.go
- lnwallet/dcrwallet/log.go
This fixes the expected location of the peers.json file when running an
embedded dcrwallet install in SPV mode. Previously this file was not
maintained as the path was wrong.
It also adds a commit to expose the underlying log io writer to ease debugging
in third party tools.
> dcrwallet: Fix peers.json file location

- go.mod
- go.sum
This updates the dcrwallet dependency to the latest available version, so dcrlnd is updated for the v1.7.4 patch release.
The only relevant change is fixing testnet support.
> go.mod: Update dcrwallet dep to future v1.7.4

- build/version.go
- go.mod
- go.sum
This is needed due to the updated testnet difficulty rules.
> deps: Update dcrwallet to v2.0.8

- peer/brontide.go
This adds stall detection with a subsequent disconnection in writer loop of the node. This is useful in detecting scenarios where the local peer stalled due to (for example) being previously suspended.
> peer: Add stall detection and disconnection

- lnwallet/dcrwallet/wallet.go
- lnwallet/interface_test.go
This adds the option to switch the gap policy when generating new addresses to Wrap instead of the default one. This fixes an issue where trying to generate an address for lnwallet to open or close a channel would result in an error.
Fix #169
> dcrwallet: Switch gap policy to wrap

- channeldb/channel.go
- docs/upstream-prs.csv
- htlcswitch/link_test.go
- lntest/itest/dcrlnd_maxio_test.go
- lntest/itest/lnd_test.go
- lnwallet/channel.go
- lnwallet/channel_test.go
- server.go
This brings the following upstream PRs to fix issues with force closed channels after peer reconnections:
https://github.com/lightningnetwork/lnd/pull/4915
https://github.com/lightningnetwork/lnd/pull/5231
https://github.com/lightningnetwork/lnd/pull/6655
> multi: bring upstream fixes for force closures after reconnection

- routing/route/route.go
This is more helpful during debug sessions.
> route: Log formatted ShortChannelID

- cmd/dcrlncli/main.go
This makes dcrlncli use the standard -V flag for displaying the version string. It also makes the printed string match the other Decred tools' output by printing the current runtime, GOOS and GOARCH versions.
> dcrlncli: Use standard version flag

- channeldb/db.go
- channeldb/dcrdb.go
- channeldb/payment_control.go
- channeldb/payments.go
- channeldb/payments_inflight.go
- channeldb/payments_inflight_test.go
- docs/upstream-prs.csv
- htlcswitch/payment_result.go
- htlcswitch/payment_result_test.go
- htlcswitch/switch.go
- routing/control_tower.go
- routing/mock_test.go
- routing/router.go
This index is meant to improve startup time of dcrlnd installs by removing the need to iterate through the entire set of payments in the db before continuing with channel startup.
A new index is added to the channeldb, using the payment sequence number as key to mark a given payment as still in-flight.
Once the payment is settled or fails, the entry is removed from the index.
While the code is designed to be able to work both with and without the index, no option to conditionally enable the index is exposed by the package or to the user, thus the index is always used. In the future, if this index is deemed as slowling down usage (as opposed to speeding up startup), then an option may be added to the node.
Unit tests are included to test fetching of in-flight payments both with and without …
> channeldb: add inflight payments index 

- chainscan/csdrivers/remotedcrwdriver.go
- chainscan/util_test.go
- go.mod
- go.sum
This was still erroneously used due to some gcs/v3/blockcf2 imports.
> build: Drop gcs/v3

- cmd/dcrlncli/cmd_invoice.go
- rpcserver.go
Previously, this was checked only when the invoice was specified for atoms.
> multi: Check invoice receive capacity in milli-atoms

- build/version.go
- channeldb/codec.go
- channeldb/db.go
- channeldb/db_test.go
- channeldb/dcrdb.go
- channeldb/dcrmigrations/migration01/codec.go
- channeldb/dcrmigrations/migration01/dcrmigration01.go
- channeldb/dcrmigrations/migration01/dcrmigration01_test.go
- channeldb/dcrmigrations/migration01/log.go
- channeldb/log.go
- channeldb/migration20/codec.go
- channeldb/migration20/migration.go
- channeldb/migration21/current/current_codec.go
- channeldb/migration21/legacy/legacy_codec.go
- channeldb/migration_01_to_11/codec.go
- docs/release-notes/release-notes-0.5.1.md
- funding/manager.go
- utxonursery.go
This migration fixes the prior migration 20, introduced when porting the upstream code.
That migration erroneously encoded outpoints without the Tree field that exists in decred code, thus rendering the index incorrect.
The new migration corrects the issue by assuming the tree of every entry is zero, which is true because the channels can only reside in regular (as opposed to stake) transactions.
One way this could cause problems was when closing or detecting closed channels that were created before the migration took place. Closing them could fail with "missing outpoint from index".
While this fixes the issue for nodes that upgrade, this does not handle channels that were already closed for nodes that are already running v0.5.0.
> channeldb: Fix migration 20 incorrect outpoint serialization

- channeldb/dcrdb.go
- channeldb/dcrmigrations/migration02/dcrmigration02.go
- channeldb/dcrmigrations/migration02/dcrmigration02_test.go
- channeldb/dcrmigrations/migration02/log.go
- channeldb/log.go
- discovery/gossiper.go
- discovery/gossiper_state.go
- discovery/syncer.go
This fixes an issue in the deployed network where nodes sending ChannelUpdates and NodeAnnouncements set to a future timestamp could cause the gossip syncer to fail to fetch new announcements.
The issue stems from the fact that the gossip syncer stores the timestamp of the last received message and uses that, upon restart, to fetch new messages. An update with a timestamp in the future propagating through the network would cause the syncer to fail to fetch new updates.
This PR fixes the issue by amending the handling of future timestamps in the syncer and by performing a database migration that rewinds any timestamps stored that are set to a future date.
> Fix gossip timestamps set to a future date

- log.go
- peer/brontide.go
- peer/log.go
This switches the peer to log ping/pong messages using a separate logger with a dedicated subsystem tag. This is useful when running in debug mode for extended periods of time, as ping messages are generally useless but repeat constantly, needlessly growing the size of log files and making debug harder.
> peer: Use a dedicated ping logger

- go.mod
- go.sum
- routing/missioncontrol_store.go
- routing/missioncontrol_store_test.go
- routing/router_test.go
This is a port of the upstream PR https://github.com/lightningnetwork/lnd/pull/8549
> Misson Control Store: Improve performance

- Makefile
- docs/release-notes/release-notes-0.7.0.md
- lntest/itest/lnd_open_channel_test.go
- Change the binaries used in integration tests to use the recently tagged release-v2.0.0 binaries.
- Add v0.7.0 release notes.
> Add release notes for v0.7.0

- chainntnfs/interface.go
This was changed at some point in dcrd, so it need to be fixed here.
> chainntnfs: Fix detection for no txindex error

- config_builder.go
When using dcrlnd as a daemon, the config builder sets the gap limit to 0, causing the wallet to crash.
This PR fixes the issue.
> fix gap limit set as 0

- go.mod
- go.sum
- lnwallet/dcrwallet/loader/loader.go
The existing LN interfaces (dcrlncli, decrediton, gRPC) do not support mixing from an embedded wallet instance. This commits disables mixing to avoid unnecessary load in dcrlnd wallets.
> dcrwallet: Disable mixing by default
